# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Jekyll

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  data:
    path: _data
    output: false
  pages:
    path: ''
    output: true
    filter: strict
  team_members:
    output: true
    path: _team_members
  resource_topics:
    output: true
    path: _resource_topics
  blog/posts:
    path: blog/_posts
    output: true
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
  academy/posts:
    path: academy/_posts
    output: true
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
  showcase/datascience/posts:
    path: showcase/datascience/_posts
    output: true
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
  showcase/powerbi/posts:
    path: showcase/powerbi/_posts
    output: true
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:

# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source:

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: _data
  collections: ''
  layouts: _layouts
  static: ''
  uploads: uploads
  includes: _includes
  dam_uploads: ''
  dam_static: ''

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC
